create table if not exists public.keep_alive_events (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  source text not null default 'vercel_cron'
);

alter table public.keep_alive_events enable row level security;

drop policy if exists "No public keep alive access" on public.keep_alive_events;

create index if not exists idx_keep_alive_events_checked_at
on public.keep_alive_events(checked_at desc);
